"""Optional Calibre integration tests for AZW3 conversion (Milestone 4.3).

These tests run the real Calibre ``ebook-convert`` executable and are **not**
part of the deterministic core suite. They are skipped cleanly when Calibre
is unavailable and never require installing Calibre, and nothing is
downloaded here.

Executable discovery mirrors the conversion layer: the ``CALIBRE_CONVERT``
environment variable takes precedence, otherwise ``ebook-convert`` is looked
up on ``PATH`` (for example ``C:\\Program Files\\Calibre2\\ebook-convert.exe``
on Windows).

Enable on a machine without Calibre on PATH:

    CALIBRE_CONVERT="C:/Program Files/Calibre2/ebook-convert.exe" python -m pytest

The fixture EPUB is generated deterministically on the fly with the project's
own ``build_epub``: no internet, no real books, no fixture files.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

import pytest

from kindle_converter.document import (
    Book,
    BookMetadata,
    Chapter,
    Image,
    Paragraph,
)
from kindle_converter.epub import (
    AZW3BackendUnavailableError,
    build_epub,
    convert_epub_to_azw3,
)


def _discover_calibre() -> str | None:
    """Return an explicit ``ebook-convert`` path, or ``None``."""
    env = os.environ.get("CALIBRE_CONVERT")
    if env:
        return env
    return shutil.which("ebook-convert")


@pytest.fixture(scope="module")
def calibre_exe() -> str:
    """Path to a usable Calibre executable; skips the request when absent."""
    path = _discover_calibre()
    if path is None:
        pytest.skip(
            "Calibre's ebook-convert executable was not found: set "
            "CALIBRE_CONVERT or add ebook-convert to PATH to run the "
            "Calibre integration tests"
        )
    return path


@pytest.fixture(scope="module")
def synthetic_epub(tmp_path_factory) -> Path:
    """A small, deterministic EPUB generated by the project's own builder."""
    tmp_path = tmp_path_factory.mktemp("calibre_fixture")
    book = Book(
        metadata=BookMetadata(title="M4.3 Calibre Integration Fixture"),
        chapters=[
            Chapter(
                title="Chapter 1",
                blocks=[
                    Paragraph(
                        text=(
                            "Deterministic synthetic EPUB for the M4.3 "
                            "optional Calibre integration test."
                        )
                    )
                ],
            )
        ],
    )
    target = tmp_path / "fixture.epub"
    build_epub(book, target)
    return target


class TestCalibreIntegration:
    def test_epub_to_azw3_produces_nonempty_output(
        self, synthetic_epub: Path, calibre_exe: str, tmp_path: Path
    ) -> None:
        destination = tmp_path / "converted.azw3"
        result = convert_epub_to_azw3(
            synthetic_epub, destination, calibre_path=calibre_exe
        )
        assert destination.exists()
        assert destination.is_file()
        assert destination.stat().st_size > 0
        assert result.source == synthetic_epub
        assert result.destination == destination

    def test_covered_epub_to_azw3_produces_nonempty_output(
        self, calibre_exe: str, tmp_path: Path
    ) -> None:
        # M4.4: a covered EPUB (cover image, cover page, name="cover"
        # metadata, cover-image manifest property) must survive the kind
        # of conversion the pipeline produces just as a coverless one does.
        source = tmp_path / "covered.epub"
        book = Book(
            metadata=BookMetadata(title="Covered Calibre Fixture"),
            chapters=[
                Chapter(
                    title="Chapter 1",
                    blocks=[
                        Paragraph(
                            text=(
                                "Deterministic synthetic covered EPUB for the "
                                "optional M4.4 Calibre integration test."
                            )
                        )
                    ],
                )
            ],
        )
        book.cover = Image(
            data=b"\x89PNG\r\n\x1a\n\x00\x01\x02\x03",
            content_type="image/png",
        )
        build_epub(book, source)

        destination = tmp_path / "covered.azw3"
        result = convert_epub_to_azw3(
            source, destination, calibre_path=calibre_exe
        )
        assert destination.exists()
        assert destination.is_file()
        assert destination.stat().st_size > 0
        assert result.source == source
        assert result.destination == destination

    def test_missing_calibre_path_raises_project_error(
        self, synthetic_epub: Path, tmp_path: Path
    ) -> None:
        # Deterministic even without Calibre: a nonexistent explicit path
        # must produce the dedicated project error, never a raw OSError.
        missing = tmp_path / "missing-ebook-convert.exe"
        with pytest.raises(AZW3BackendUnavailableError) as excinfo:
            convert_epub_to_azw3(
                synthetic_epub, tmp_path / "out.azw3", calibre_path=missing
            )
        assert "ebook-convert" in str(excinfo.value)